### ISSUE TITLE
Deprecated formatting rules

### ISSUE THREAD

**Issue by horneac** [cloudflightio/cloudflight-eslint-plugin#221]
Formatting rules were deprecated in eslint and typescript-eslint as they are hard to maintain and eslint is maybe not the right tool for the job. 
https://eslint.org/blog/2023/10/deprecating-formatting-rules/ 
They are recommending switching to tools made for this purpose like prettier or dprint. There is also the option to keep using eslint @stylistic plugin as these are still maintained. 
Do you recommend anything? And what is the plan for this plugin going forward?

**Comment by strawberry-choco** [comment]
For now we plan to observe the ecosystem till eslint releases version 9. Based on the situation right now, https://github.com/eslint-stylistic/eslint-stylistic seems to be our way forward, but nothing is decided yet.

We had prettier as our default formatting tool before, but it's output is hard to read, since prettier does not consider the context of the code. That is why we switched to the solution we have now.
